export { CustomerStatusBadge } from "./components/CustomerStatusBadge"
export { CustomerTable } from "./components/CustomerTable"
export { CustomerForm } from "./components/CustomerForm"
export { customerKeys, useCustomers, useCustomer, useCustomerOrders, useCustomerAddresses, useCustomerAccount, useCreateCustomer, useUpdateCustomer, useBlacklistCustomer } from "./hooks/useCustomers"
export { customerSchema } from "./schemas/customer.schema"
export type { CustomerFormValues } from "./schemas/customer.schema"
export type { Customer, CustomerSegment, CustomerAddress, CreateCustomerRequest, UpdateCustomerRequest, CustomerOrderSummary } from "./types/customer.types"
